### ISSUE TITLE
Allow using a url for the input file

### ISSUE THREAD

**Issue by matmaxgeds** [kndm/iati-diff#18]
At the moment, we pass an already downloaded input file, but if a url is supplied, we should parse/download it and use it from there

**Comment by matmaxgeds** [comment]
e.g. https://test-datastore.iatistandard.org/api/activities/?recipient_country=SO&fields=all&page_size=5 or for a single activity: https://test-datastore.iatistandard.org/api/activities/XM-OCHA-FTS-240437/?format=xml&fields=all.......this on is broken right this moment

**Comment by kndm** [comment]
Functionality has been added

**Comment by matmaxgeds** [comment]
Not according to the readme?

**Comment by kndm** [comment]
Readme push didn't go through due to a pull of the file missing, fixed.
