### ISSUE TITLE
Need to add instructions on how to run it to the readme

### ISSUE THREAD

**Issue by matmaxgeds** [kndm/iati-diff#3]
@kndm I tried two ways and both got errors:

matt@Birch:~/Cloud/Syncthing/Laptop/Downloads/IATIdiff$ python3 iati-diff.py
Traceback (most recent call last):
  File "iati-diff.py", line 9, in <module>
    tree = ET.parse(sys.argv[1])
IndexError: list index out of range

matt@Birch:~/Cloud/Syncthing/Laptop/Downloads/IATIdiff$ python3 iati-diff.py activity-list\(2\).xml
iati-diff.py:39: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if new_data:
Traceback (most recent call last):
  File "iati-diff.py", line 40, in <module>
    with open('./activities/' + current_identifier + '.xml', 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: './activities/CH-4-2008004812.xml'
matt@Birch:~/Cloud/Syncthing/Laptop/Downloads/IATIdiff$

**Comment by kndm** [comment]
@matmaxgeds noted. Instructions currently being added to the readme.
Error was due to some folder not having been pushed.

**Comment by matmaxgeds** [comment]
I still get:

matt@Birch:~/Cloud/Syncthing/Laptop/Downloads/IATIdiff$ python3 iati-diff.py activity-list\(2\).xml
iati-diff.py:36: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if new_data:
Traceback (most recent call last):
  File "iati-diff.py", line 37, in <module>
    with open('./activities/' + current_identifier + '.xml', 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: './activities/CH-4-2008004812.xml'

do I need to download all the folders as well - or does the script make those folders before it needs them?

**Comment by kndm** [comment]
@matmaxgeds If you pull the latest repo the folder should be there with it.

**Comment by matmaxgeds** [comment]
Sure......but that is a bit against the point of a script - please make the script make the folders

**Comment by matmaxgeds** [comment]
Closing here and making new issues
