### ISSUE TITLE
Turn output into CSV instead of a plain TXT file

### ISSUE THREAD

**Issue by kndm** [kndm/iati-diff#4]
Currently the output is coming as a plain .txt file, must turn into csv for better visualization.

**Comment by matmaxgeds** [comment]
If you can solve the \n newline issue then you can just write it out with a different file ending - but probs better to use python csv export

**Comment by matmaxgeds** [comment]
We also agreed that this would be one CSV file, not separate ones so don't need the folder for this.

In case we ran it on a lot of activities, the script should append each activity to the CSV not keep the whole set in memory and write them all out at the end.

**Comment by kndm** [comment]
> We also agreed that this would be one CSV file, not separate ones so don't need the folder for this.
> 
> In case we ran it on a lot of activities, the script should append each activity to the CSV not keep the whole set in memory and write them all out at the end.

Will do, as this script was made separately at that time (the time in which we decided one CSV would be fine) it is not updated to that point. I will be updating tonight on keeping these CSVs into one.

**Comment by kndm** [comment]
Has been fixed
